### ISSUE TITLE
pcre.backtrack_limit is set too small.

### ISSUE THREAD

**Issue by johnblommers** [Hi-Folks/ibis-next#27]
So I was building a very large PDF file with over 5,000 pages. Before ibis-next finished building it an error occurred:

> ✨✨ 5870 PDF pages ✨✨  
>
> In `Mpdf.php` line 27072:  
>
>  The HTML code size is larger than `pcre.backtrack_limit 1000000`. You should use `WriteHTML()` with smaller string lengths. Pass your HTML in smaller chunks.  
>
> `pdf [-c|--content [CONTENT]] [-d|--workingdir [WORKINGDIR]] [--] [<theme>]`

The fix is to edit `/etc/php/8.1/cli/php.ini` and find the line where `pcre.backtrack_limit` is defined. It's commented out. Remove the leading semicolon and change the value to 5000000.

**Comment by roberto-butti** [comment]
Thank you for the feedback @johnblommers .
I am happy to know that you are testing the tool with a so huge PDF file.

The PDF is progressively built, converting one markdown file at a time. I'd like to understand how to improve the underlying logic for more efficient parsing and conversion. Could you tell me (if you have the time) how many markdown files you are using and the size in bytes of each one?

Thank you.

**Comment by johnblommers** [comment]
> TCould you tell me (if you have the time) how many markdown files you are using and the size in bytes of each one?

There are 170 Markdown files in my `content` directory. Here are their sizes in bytes, sorted from largest to smallest:

621461
440914
438003
424627
386688
359562
304998
247316
228713
223628
195570
187056
185253
174541
169823
166498
160512
159266
151508
140382
137731
136422
130272
123947
123098
121586
120649
120049
111121
105597
105317
100344
94391
82476
80694
78868
78597
77803
71899
71652
67884
67570
66350
61484
60802
53926
52769
52298
50714
48081
47616
45122
43550
42211
42115
39690
37760
36028
35300
33031
32341
30339
29948
29791
29220
26780
26059
24935
24087
23547
22696
22449
21766
21446
20978
20865
18606
18535
17696
17530
17472
17151
16650
15614
14258
14170
13621
13305
13077
12839
12031
11909
11181
11165
10993
10467
10302
10190
9966
9844
8790
8530
8487
8206
8053
8019
7933
7509
7370
7144
6893
6588
6210
5931
5924
5775
5697
5639
5602
5390
5069
4877
4743
4505
4465
4383
4326
4152
3951
3910
3873
3768
3736
3687
3649
3620
3389
3335
3226
3225
3221
3114
3100
3062
2877
2475
2461
2368
2362
2184
2144
2106
1921
1769
1554
1535
1530
1379
1366
1273
1210
1094
926
838
385
357
346
341
144
36

There is one file not listed above which is 362,289 bytes long. By itself IBIS-NEXT will convert it to a PDF, but when included in the `content` directory there is a problem I have to dig into before reporting it.

For completeness let me add that about 740 images are referenced within those 170 Markdown files. Together the images occupy about 122.2 MB storage.

**Comment by roberto-butti** [comment]
Going to close it thanks to your workaround. If someone else will have the same issue we can suggest: to set `pcre.backtrack_limit`
